# Site Metadata
base_url = "https://nao.id.au"
title = "Naomi's Stuff"
description = ""
# Site Generation Options
compile_sass = true
build_search_index = true
include_title = true
include_content = true
truncate_content_length = 100
generate_feed = true
# Markdown Rendering Options
[markdown]
highlight_code = true
highlight_theme = "monokai"
# Extra Data
[extra]
